config/routes.rb
CrawlerDb::Application.routes.draw do
  resources :vulnerabilities

  resources :messages, :only => [:index, :create, :destroy]
  
  match 'dump' => 'messages#dump'
  match 'clear' => 'vulnerabilities#clear'

  root :to => 'index#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :vulnerability
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    
  end
end

app/controllers/messages_controller.rb
require 'uri'
require 'digest/sha1'

class MessagesController < ApplicationController
  def index
    @page = params[:page].to_i > 0 ? params[:page].to_i : 1
    @pages = (Message.count / 500.0).ceil
    @pages = 1 if @pages == 0
    @page = 1 if @page > @pages
    @messages = Message.limit(500).offset((@page - 1) * 500)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end
  
  def create
    vid = params[:message][:vulnerability_id]
    if vid.to_i == 0
      vid = Vulnerability.find_by_name(vid).id rescue nil
    end
    params[:message][:vulnerability_id] = vid unless vid.nil?
    
    url_hash = Digest::SHA1.hexdigest params[:message][:url]
    uri = URI.parse params[:message][:url]
    
    scheme = uri.scheme.nil? ? "" : uri.scheme + "://"
    url = params[:message][:url] = scheme + (uri.host || "") + (uri.path || "")

    @message = Message.find_by_url_and_vulnerability_id_and_text(url, params[:message][:vulnerability_id], params[:message][:text])
    if @message.nil?
      params[:message][:count] = 1
      params[:message][:url] = url
      params[:message][:url_hash] = url_hash
      @message = Message.new(params[:message]) 
    else
      @message.count = @message.count + 1
    end

    respond_to do |format|
      if vid.nil?
        format.json { render json: "Error: Improper vulnerability_id", status: :unprocessable_entity }
      elsif @message.save
        format.json { render json: @message, status: :created, location: @message }
      else
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def dump
    pages = (Message.count / 500.0).ceil
    pages = 1 if pages == 0
    done = params[:page].to_i == pages
    respond_to do |format|
      format.json { render json: { "done" => done, "messages" => Message.limit(500).offset((params[:page].to_i - 1) * 500) }.to_json }
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :ok }
    end
  end
end

app/controllers/vulnerabilities_controller.rb
class VulnerabilitiesController < ApplicationController
  def index
    @vulnerabilities = Vulnerability.all
    
    # HARD-CODED STATS:
    @cookies1 = Message.find_all_by_vulnerability_id(31).select { |m| !m.crawler && m.text == "Secure website set a non-secure cookie!" }
    @cookies2 = Message.find_all_by_vulnerability_id(31).select { |m| !m.crawler && m.text == "Non-secure website set a secure cookie!" }
    @xml1 = Message.find_all_by_vulnerability_id(7).select { |m| !m.crawler && m.text == "Website called a SYNCHRONOUS request" }
    @xml2 = Message.find_all_by_vulnerability_id(7).select { |m| !m.crawler && m.text == "Website called setRequestHeader()" }
  end

  def show
    @vulnerability = Vulnerability.find(params[:id])
    @page = params[:page].to_i > 0 ? params[:page].to_i : 1
    @pages = (@vulnerability.messages.count / 500.0).ceil
    @pages = 1 if @pages == 0
    @page = 1 if @page > @pages
    @messages = @vulnerability.messages.limit(500).offset((@page - 1) * 500)
  end

  def new
    @vulnerability = Vulnerability.new
  end

  def edit
    @vulnerability = Vulnerability.find(params[:id])
  end

  def create
    @vulnerability = Vulnerability.new(params[:vulnerability])

    if @vulnerability.save
      redirect_to vulnerabilities_path, notice: 'Vulnerability was successfully created.'
    else
      render action: "new"
    end
  end
  
  def update
    @vulnerability = Vulnerability.find(params[:id])

    if @vulnerability.update_attributes(params[:vulnerability])
      redirect_to vulnerabilities_path, notice: 'Vulnerability was successfully updated.'
    else
      render action: "edit"
    end
  end
  
  def clear
    Message.destroy_all(:vulnerability_id => params[:id])
    redirect_to vulnerabilities_path
  end

  def destroy
    @vulnerability = Vulnerability.find(params[:id])
    @vulnerability.destroy

    redirect_to vulnerabilities_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/vulnerabilities_helper.rb
module VulnerabilitiesHelper
end

app/views/index/index.html.haml
#home_page
  %h1
    Flip A Bit DB
  %p
    To post a new instance of a vulnerability, make a POST request to "https://dustingtheweb.herokuapp.com/messages" with a JSON in the format of: 
  %p  
    { message: { url: "www.google.com", vulnerability_id: 1, text: "optional text", crawler: false } }
    
  %p
    The vulnerability_id can be either the id or the specific name ( both can be found
    = link_to "here", vulnerabilities_path
    ) You can also get a dump of all of the raw data so far by making a GET request to "https://dustingtheweb.herokuapp.com/dump" with a "page" parameter (each request is limited to 500 tuples). Run the db_extract script to get all data.
  
  %p
    %b
      NOTE:
    probably not a good idea to go to the Raw Data page unless you need to, since it displays all of the data
  
  #example
    %p
      Click below to create a sample document.domain message 
      %b
        %i
          (this is for db testing)
    %a{:href => "#", :id => "sample"}
      Create Sample Message
  
  :javascript
    $("#sample").click(function() {
      $.post("/messages", { message: { url: "www.google.com", vulnerability_id: "document.domain", text: "THIS IS AN EXAMPLE MESSAGE", crawler: true } });
    });

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CrawlerDb
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #page
      #header_links
        = link_to "Home", root_path
        |
        = link_to "Vulnerabilities", vulnerabilities_path
        |
        = link_to "Raw Data", messages_path
      #page_body
        = yield

app/views/messages/_data_table.html.haml
%table
  %tr
    %th Count
    %th Url
    %th Vulernability
    %th Text
    %th
  - @messages.each do |message|
    %tr
      %td.short= message.count
      %td.long= message.url.length > 40 ? message.url[0..36] + "..." : message.url
      %td.short= message.vulnerability_id
      %td.long= message.text.length > 40 ? message.text[0..36] + "..." : message.text
      %td.short= link_to 'Delete', message, confirm: 'Are you sure?', method: :delete

app/views/messages/index.html.haml
#messages_page
  %h1 Raw Data
  
  #pagination_controls
    -if @page == 1
      .plink
        <<
      .plink
        <
    -else
      .plink
        = link_to "<<", messages_path(:page => 1)
      .plink
        = link_to "<", messages_path(:page => @page - 1)
    = "page #{@page} of #{@pages}"
    - if @page == @pages
      .plink
        >
      .plink
        >>
    - else
      .plink
        = link_to ">", messages_path(:page => @page + 1)
      .plink
        = link_to ">>", messages_path(:page => @pages)
  
  = render 'data_table'

app/views/vulnerabilities/_form.html.erb
<%= form_for(@vulnerability) do |f| %>
  <% if @vulnerability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vulnerability.errors.count, "error") %> prohibited this vulnerability from being saved:</h2>

      <ul>
      <% @vulnerability.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vulnerabilities/edit.html.erb
<h1>Editing vulnerability</h1>

<%= render 'form' %>

<%= link_to 'Show', @vulnerability %> |
<%= link_to 'Back', vulnerabilities_path %>

app/views/vulnerabilities/index.html.haml
#vul_page
  %h1
    Vulnerability Statistics
  #new_vul_link
    = link_to "New Vulnerability", new_vulnerability_path
  %table
    %tr
      %th Uniq Pgs
      %th Uniq Dmns
      %th Name
      %th 
      %th
      %th
    - @vulnerabilities.each do |vul|
      %tr
        %td.short= vul.messages.reject { |m| m.crawler }.collect { |m| m.hash }.uniq.count
        %td.short= vul.messages.reject { |m| m.crawler }.collect { |m| URI.parse(m.url).host }.uniq.count
        %td.long
          %a{ :href => vulnerability_path(vul) }
            = vul.name + " (id: #{vul.id})"
        %td.short= link_to 'Edit', edit_vulnerability_path(vul)
        %td.short= link_to 'Clear', clear_path(:id => vul.id), confirm: 'Are you sure you want to clear all data for this vulnerability?'
        %td.short= link_to 'Delete', vul, confirm: 'Are you sure you want to delete this vulnerability and all its data?', method: :delete
  #other_stats
    %h2
      Other Stats
    = "Unique secure pages that set a non-secure cookie: #{@cookies1.collect { |m| m.hash }.uniq.count}"
    %br
    = "Unique secure domains that set a non-secure cookie: #{@cookies1.collect { |m| URI.parse(m.url).host }.uniq.count}"
    %br
    = "Unique non-secure pages that set a secure cookie: #{@cookies2.collect { |m| m.hash }.uniq.count}"
    %br
    = "Unique non-secure domains that set a secure cookie: #{@cookies2.collect { |m| URI.parse(m.url).host }.uniq.count}"
    %br
    %br
    = "Unique pages that send synchronous XHRs: #{@xml1.collect { |m| m.hash }.uniq.count}"
    %br
    = "Unique domains that send synchronous XHRs: #{@xml1.collect { |m| URI.parse(m.url).host }.uniq.count}"
    %br
    = "Unique pages that setRequestHeader: #{@xml2.collect { |m| m.hash }.uniq.count}"
    %br
    = "Unique domains that setRequestHeader: #{@xml2.collect { |m| URI.parse(m.url).host }.uniq.count}"

app/views/vulnerabilities/new.html.erb
<h1>New vulnerability</h1>

<%= render 'form' %>

<%= link_to 'Back', vulnerabilities_path %>

app/views/vulnerabilities/show.html.haml
#show_vul_page
  %h1
    = @vulnerability.name
    
  #pagination_controls
    -if @page == 1
      .plink
        <<
      .plink
        <
    -else
      .plink
        = link_to "<<", vulnerability_path(:id => @vulnerability.id, :page => 1)
      .plink
        = link_to "<", vulnerability_path(:id => @vulnerability.id, :page => @page - 1)
    = "page #{@page} of #{@pages}"
    - if @page == @pages
      .plink
        >
      .plink
        >>
    - else
      .plink
        = link_to ">", vulnerability_path(:id => @vulnerability.id, :page => @page + 1)
      .plink
        = link_to ">>", vulnerability_path(:id => @vulnerability.id, :page => @pages)
  
  = render 'messages/data_table'